Fix destroy all functionality
```
$ bundle exec hatchet destroy --all
home/travis/.rvm/gems/ruby-2.5.3/gems/heroku_hatchet-7.1.0/lib/hatchet/reaper.rb:83:in `destroy_all': undefined local variable or method `get_apps' for #<Hatchet::Reaper:0x000000000317f400> (NameError)
from /home/travis/.rvm/gems/ruby-2.5.3/gems/heroku_hatchet-7.1.0/bin/hatchet:112:in `destroy'
from /home/travis/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
from /home/travis/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
from /home/travis/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
from /home/travis/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
from /home/travis/.rvm/gems/ruby-2.5.3/gems/heroku_hatchet-7.1.0/bin/hatchet:186:in `<top (required)>'
from /home/travis/.rvm/gems/ruby-2.5.3/bin/hatchet:23:in `load'
from /home/travis/.rvm/gems/ruby-2.5.3/bin/hatchet:23:in `<main>'
from /home/travis/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
from /home/travis/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
```